### ISSUE TITLE
RosTensorFlow instance has no attribute '_session'

### ISSUE THREAD

**Issue by shixinlishixinli** [shunchan0677/Tensorflow_in_ROS#2]
hello 
 i use ubuntu 14.04 , ros indigo and tensorflow 1.0 .there is a node pub  image . and i use your program to receive image , but there is something wrong about _session .i am sure the topic and image type is right .
i am looking forward to your reply

AttributeError: RosTensorFlow instance has no attribute '_session'

**Comment by shunchan0677** [comment]
Thank you for asking.

Sorry, I don't understand why the error caused.
My PC which is ubuntu14.04, ros indigo, tensorflow0.12 and Python 2.7.6 can use this code.

Can you please tell me about your python version and the full error message?

**Comment by shixinlishixinli** [comment]
i think my frequency is too high and there is no time to initialize '_session',and i put initialization before sub ,all things is ok

**Comment by shunchan0677** [comment]
Oh, Did you solve this issue?

**Comment by shixinlishixinli** [comment]
yes i have solved this issus

**Comment by shunchan0677** [comment]
That's good.
I close this issue.

Thank you.

**Comment by shunchan0677** [comment]
I put initialization before sub now. Thank you so much!!
